cookie:
  expiry_days: 30
  key: humand-sales-insights-secret-cookie-key-2024
  name: humand_insights_auth
credentials:
  usernames:
    agustina.ini:
      email: agustina.ini@humand.co
      failed_login_attempts: 0
      first_name: Agus
      last_name: Ini
      logged_in: false
      password: $2b$12$FOvij58iAnm16klIGLhaE.6ke1j4jTRykc8uQF6d7LlVut4aNqS3C
      roles:
      - viewer
    aimee:
      email: aimee@humand.co
      failed_login_attempts: 0
      first_name: Aimee
      last_name: ''
      logged_in: false
      password: $2b$12$WzTJ1rtOEf.kVZTs9Z8SNOA.mtKpweoaJfTr8bBrD/LToRHHcdKKm
      roles:
      - viewer
    augusto.ferrer:
      email: augusto.ferrer@humand.co
      failed_login_attempts: 0
      first_name: Augusto
      last_name: Ferrer
      logged_in: false
      password: $2b$12$NamiW6VbImi8tAG/vV26uOn06JAWMXBtAb3BRTmqEg.3Luu/.Z6a.
      roles:
      - viewer
    caro:
      email: caro@humand.co
      failed_login_attempts: 0
      first_name: Carolina
      last_name: Mendiondo
      logged_in: false
      password: $2b$12$b73nohSTp1pGbx3T9nKLYua479dp1sYQ1rLqqSC5C4QofS2zB4..2
      roles:
      - user
    guilherme.fernandes:
      email: guilherme.fernandes@humand.co
      failed_login_attempts: 0
      first_name: Guilherme
      last_name: Fernandes
      logged_in: false
      password: $2b$12$vZ7lMFEAg6YgQNd595sxmucOwUmNf7dwRpwfoHYq4JldOTn/QzjVS
      roles:
      - campaign_advisor
      - viewer
    dana.goin:
      email: dana.goin@humand.co
      failed_login_attempts: 0
      first_name: Dana
      last_name: Goin
      logged_in: false
      password: $2b$12$AHbiJMn7d3TK9gq/beLcDe13iM0s.Y.mD5Hgc7zeltQ.Pzow4dguy
      roles:
      - marketing
    daniel.moreno:
      email: daniel.moreno@humand.co
      failed_login_attempts: 0
      first_name: Daniel
      last_name: Moreno
      logged_in: false
      password: $2b$12$DqiTbXIamO4xCOu/DiaeauWxK8OpBrq/KIUGpaLn8Cftd1N8dxeb.
      roles:
      - user
    daniela.lopez:
      email: daniela.lopez@humand.co
      failed_login_attempts: 0
      first_name: Daniela
      last_name: Lopez
      logged_in: false
      password: $2b$12$.wh.xkCrPMOiabXH2SAXM.n/K.8.n404JPdclnwjdzDfv2DSSHe1S
      roles:
      - campaign_advisor
      - viewer
    juan.diego.alcocer:
      email: juan.diego.alcocer@humand.co
      failed_login_attempts: 0
      first_name: Juandi
      last_name: Alcocer
      logged_in: false
      password: $2b$12$twTNt.4ruJEL0fxo.BMZvOSV/Ls5uq67669Lm2IE7SPn0BsQma2CO
      roles:
      - viewer
    juanba.scelzi:
      email: juanba.scelzi@humand.co
      failed_login_attempts: 0
      first_name: Juanba
      last_name: Scelzi
      logged_in: false
      password: $2b$12$XZj.bOdEV3c7mk66ZRfeaO6AaMWU93l/vol7zGn/ieXUtnYjqkrw6
      roles:
      - admin
    luciano.paradiso:
      email: luciano.paradiso@humand.co
      failed_login_attempts: 0
      first_name: Lucho
      last_name: Paradiso
      logged_in: false
      password: $2b$12$JWqlgLQeV3AZld1xUJY2EOMzyYb3L7/LvIVNIJIn34CtJGt.z7yZq
      roles:
      - viewer
    manuela.cavallo:
      email: manuela.cavallo@humand.co
      failed_login_attempts: 0
      first_name: Manuela
      last_name: Cavallo
      logged_in: false
      password: $2b$12$JC7uxRhAda/Q.zF6SunNrOWlBdipJjufxh5T6shz1yvYbgVHvChVG
      roles:
      - viewer
    marcos.palacio:
      email: marcos.palacio@humand.co
      failed_login_attempts: 0
      first_name: Marcos
      last_name: Palacio
      logged_in: false
      password: $2b$12$ltDv46FPA.9ubL/DoOzltukjEbzGFsJLNlujg0tzg7wO64ZRAQP0G
      roles:
      - viewer
    melissa.gonzalez:
      email: melissa.gonzalez@humand.co
      failed_login_attempts: 0
      first_name: Melissa
      last_name: Gonzalez
      logged_in: false
      password: $2b$12$dqyWKM0Vik4k/oCt1Rb9.uRegO.xikGvC1xdYIjxmn/xY7T32lh0q
      roles:
      - campaign_advisor
      - viewer
    mile:
      email: mile@humand.co
      failed_login_attempts: 0
      first_name: Milena
      last_name: Yuri
      logged_in: false
      password: $2b$12$QchJEoL6JE7Q.zc4UCxcLeT.iSM.FrBqnMRgB26mSdsON63sueCyO
      roles:
      - campaign_advisor
      - viewer
    nico.cordes:
      email: nico.cordes@humand.co
      failed_login_attempts: 0
      first_name: Nico
      last_name: Cordes
      logged_in: false
      password: $2b$12$9zZKOOoyJg7Yl91.9cDZbedT9jHrCGfKhMOm4t0qAmdLrhbjOYId.
      roles:
      - viewer
    pedro:
      email: pedro@humand.co
      failed_login_attempts: 0
      first_name: Pedro
      last_name: ''
      logged_in: false
      password: $2b$12$c/1n09t29UpAYtu5EgFgde0PDXAJL9j.xnXQKf0rfKb1Gqs7r7rYe
      roles:
      - campaign_advisor
      - viewer
    raphael.montressor:
      email: raphael.montressor@humand.co
      failed_login_attempts: 0
      first_name: Raphael
      last_name: Montressor
      logged_in: false
      password: $2b$12$sEYDjzIjRmbpB7hTymTIBu/oPbkOjo4BXIjFXxlYr8ZoW2Nmvfype
      roles:
      - campaign_advisor
      - viewer
    salvador.castrobay:
      email: salvador.castrobay@humand.co
      failed_login_attempts: 0
      first_name: Salvador
      last_name: Castro Bay
      logged_in: true
      password: $2b$12$MgnOVLaK9uRYOKfbTXhb1eYpkIGvd28O40C7qem5Xu1N9fkjIRuA6
      roles:
      - admin
    sofia.esposito:
      email: sofia.esposito@humand.co
      failed_login_attempts: 0
      first_name: "Sof\xEDa"
      last_name: Esposito
      logged_in: false
      password: $2b$12$GZbTTzWwLDimBRcnoeRJlu6nvWIxZtq0XFQ0fHTJFaXVK9B65E1cu
      roles:
      - user
    soledad.barca:
      email: soledad.barca@humand.co
      failed_login_attempts: 0
      first_name: Sole
      last_name: Barca
      logged_in: false
      password: $2b$12$f7MjRwBhTCHKwNUf6.pLpeeuN5ZorT4ESnGnzY2vQPbCRDtIVg4DK
      roles:
      - viewer
    vanina.moreira:
      email: vanina.moreira@humand.co
      failed_login_attempts: 0
      first_name: Vanina
      last_name: Moreira
      logged_in: false
      password: $2b$12$SN/NaA/SO2MxhdtLD5QY3.ky1YS4Soim1PqKwxArRWEtPt2Qzq7ti
      roles:
      - viewer
    vivi:
      email: vivi@humand.co
      failed_login_attempts: 0
      first_name: Vivi
      last_name: ''
      logged_in: false
      password: $2b$12$ExvM1zGIXRnewTqtyxf6c.nVo9T1kfg4C2Ay1qhzmG3OE7Hr0yCyC
      roles:
      - viewer
pre-authorized:
  emails: []
